### ISSUE TITLE
String.format over string.replace

### ISSUE THREAD

**Issue by Cethric** [shaun-h/istaflow#2]
In the creation of an `element` use `str.format` over `str.replace`
As this will only require one call to the string instead of multiple calls
This is mainly for line 47 onwards of [ElementManager.py](https://github.com/shaun-h/istaflow/blob/master/managers/ElementManager.py)
Useful information
[https://pyformat.info/](https://pyformat.info/)

EDIT
Ignore this I am creating a pull request for this issue. (Along with fixing a few other things)

**Comment by shaun-h** [comment]
no problems I will take a look at the pull requests soon, cheers
